import "./globals.css";
import Navbar from "../components/module/navbar/Navbar";
import Footer from "../components/module/footer/Footer";
import { ToastProvider } from "@/components/context/ToastContext";

export const metadata = {
  title: "اسپارک آپ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className="bg-white font-azar ">
        <Navbar />
        <ToastProvider>{children}</ToastProvider>
        <Footer />
      </body>
    </html>
  );
}
