name: CI/CD Frontend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # برای GHCR ضروری است
      id-token: write
    env:
      REGISTRY: ghcr.io
      OWNER_LC: ${{ toLower(github.repository_owner) }}
      IMAGE_NAME: ${{ toLower(github.repository_owner) }}/sparkup-frontend
      TAG: main-${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR (using GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          NEW_FRONTEND_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          NEW_BACKEND_IMAGE:  ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/sparkup-backend:latest
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          envs: NEW_FRONTEND_IMAGE,NEW_BACKEND_IMAGE
          script: |
            export NEW_FRONTEND_IMAGE
            export NEW_BACKEND_IMAGE
            /opt/sparkup/deploy.sh
