name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # به پوشه بک‌اند بروید و آخرین تغییرات را بگیرید
            echo ">>> Pulling backend changes..."
            cd ~/spark-up/sparkup-backend
            git pull 
            # به پوشه فرانت‌اند بروید و آخرین تغییرات را بگیرید
            echo ">>> Pulling frontend changes..."
            cd ~/spark-up/sparkup-new-design
            git pull

            echo ">>> Rebuilding and restarting services..."
            cd ~/spark-up
            # ایمیج‌ها را دوباره بسازید و کانتینرها را با نسخه جدید "مجبور به بازسازی" کنید
            docker compose up -d --build --force-recreate
            # ایمیج‌ها را دوباره بسازید و کانتینرها را با نسخه جدید جایگزین کنید
            docker compose up -d --build
            docker image prune -f
